### ISSUE TITLE
Front Camera Upside Down

### ISSUE THREAD

**Issue by johan-schoeman** [yuriy-budiyev/code-scanner#1]
Hi

A nice and "easy-to-implement" project. Just an issue that I came across on my Samsung S4 mini (KitKat). When using the front camera the preview is upside-down.

Thanks

**Comment by yuriy-budiyev** [comment]
Hi, thanks for the report. The issue was fixed in version 1.0.2.

**Comment by johan-schoeman** [comment]
Perfect! Working 100%!

**Comment by farislivemaker** [comment]
@yuriy-budiyev can you guide me how to use front camera ? I gone through your sample code but am unable to find the case. 

Thanks in advance!

**Comment by safield** [comment]
I am seeing this issue with the latest version of the code. The camera preview is flipped upside down.

It is on an LG Gpad 10.1 running Android 5.0.2. 

Suggest to reopen.

**Comment by safield** [comment]
I am also seeing this issue on a custom android device running Android 7.0.1

**Comment by cscovino** [comment]
I am seeing this issue too on android 7.0

Suggest to reopen.

**Comment by Nimeton60** [comment]
Acer Chromebook R11 preview is upside down.

**Comment by nicemak** [comment]
Still facing this camera, flipping up side down on front camera, library version: 2.3.2, does any have solution to it?
