### ISSUE TITLE
It is difficult to scan a barcode using a Samsung j7 prime

### ISSUE THREAD

**Issue by MIqbalFadillah** [yuriy-budiyev/code-scanner#100]
when i used the Samsung j7 prime, scanning it was very difficult.
how to solve it so that when the barcode is scanned the data is read immediately?

**Comment by raulGLD** [comment]
In my experience, this also depends on the camera and the processing power of the device you are using, and maybe also the print quality. In my case, it reads it immediately. Do you have another device to test with?

**Comment by MIqbalFadillah** [comment]
i don't know, maybe i'll try it in another device with same series. thank you sir .
