### ISSUE TITLE
Scan an existing image for QR Codes

### ISSUE THREAD

**Issue by knightcube** [yuriy-budiyev/code-scanner#103]
How do I let the user select an image from the gallery and scan a QR code in it?

**Comment by yuriy-budiyev** [comment]
See BarcodeUtils: https://github.com/yuriy-budiyev/code-scanner/blob/master/src/main/java/com/budiyev/android/codescanner/BarcodeUtils.java

**Comment by knightcube** [comment]
Thanks a bunch!
