### ISSUE TITLE
Migrate from jcenter to maven central

### ISSUE THREAD

**Issue by mpost** [yuriy-budiyev/code-scanner#110]
With the shutdown of jcenter in may 2021 the artifact needs to be migrated to mavencentral. See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ for details.

**Comment by Iseis** [comment]
Came here to see if someone had raised this issue. Glad to see this.

**Comment by thegarlynch** [comment]
Come on please

**Comment by dryasbk** [comment]
Please migrated to  maven central()

**Comment by gptshubham595** [comment]
glad that this has been raised, please migrate it

**Comment by gptshubham595** [comment]
till then you can use 🤣 
implementation 'com.github.gptshubham595:QRnew:284244296d'

will remove this once this lib is updated

**Comment by dryasbk** [comment]
I think  ZXing itself needs to migrate to maven central!!

**Comment by sham0688** [comment]
+

**Comment by Damercy** [comment]
Please migrate from `jcenter` as soon as possible.

**Comment by tnibler** [comment]
Considering the original author doesn't seem to be very active anymore I don't think this is going to happen. If anyone forks and revives this project please let everyone know.

**Comment by Nikkolas-Cage** [comment]
bump any updates with this?

**Comment by GoncaloJoaoCorreia** [comment]
you can use this with Jitpack, since they support open sourced Android projects. Just do:

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
And then
`implementation 'com.github.yuriy-budiyev:code-scanner:2.1.0'`

It's at least a workaround to keep unmaintained libraries usable

**Comment by yuriy-budiyev** [comment]
jcenter() will be downloadable until february 1st 2022

**Comment by yuriy-budiyev** [comment]
I will move to maven cantral or something else, but not now.

**Comment by bgelli** [comment]
Any news about this?

**Comment by AlanKleymeyer** [comment]
@yuriy-budiyev 
https://jcenter.bintray.com appears to be down.
Maybe this is just temporary but it would be nice to have this migration completed so we can remove jcenter from our maven scripts.
We would like to continue using and supporting your library but we may be forced to look into alternate libraries.
Thanks for providing this awesome library.

**Comment by UrielFrankel** [comment]
> @yuriy-budiyev https://jcenter.bintray.com appears to be down. Maybe this is just temporary but it would be nice to have this migration completed so we can remove jcenter from our maven scripts. We would like to continue using and supporting your library but we may be forced to look into alternate libraries. Thanks for providing this awesome library.

@AlanKleymeyer there is a solution above

**Comment by igor-brishkoski** [comment]
Bumping this.

**Comment by 4brunu** [comment]
Any news on this?

**Comment by serkansentilay** [comment]
Could not find com.github.yuriy-budiyev:code-scanner:2.1.0.

**Comment by yuriy-budiyev** [comment]
Check readme, migrated to JitPack.

**Comment by diego-antonelli** [comment]
Dear maintainers, jitpack went down for 2 days (from yesterday) and seems not reliable, can you somehow migrate it to a more reliable repo like mavenCentral or good? @yuriy-budiyev 

Reference: https://github.com/jitpack/jitpack.io/issues/5337
