### ISSUE TITLE
Not Allowing Import

### ISSUE THREAD

**Issue by JacobHornbeck** [yuriy-budiyev/code-scanner#119]
When I try to import your CodeScanner module, I keep getting an error...

To import, I have this code:
```kotlin
import com.budiyev.android.codescanner.CodeScanner
```

Android studio flags the "budiyev", and it doesn't work... what am I supposed to do?

**Comment by koderstory** [comment]
Check this [#120](https://github.com/yuriy-budiyev/code-scanner/issues/120)

**Comment by JacobHornbeck** [comment]
Thanks! That worked!
