### ISSUE TITLE
Front camera bar code scan doesn't works with android 4.4.4 with issue "failed to connect to camera services" 

### ISSUE THREAD

**Issue by farislivemaker** [yuriy-budiyev/code-scanner#12]
hay @yuriy-budiyev  your library was so good works well with back camera.But it isn't works well with front cam. 
In Android kitkat 4.4.4 when using front cam i got through a toast "failed to connect to camera services", I used the same in Android 5.0 and above, its working. 
I preferred your library mainly bcuz focus option for front cam but in my case the focus button is also disabled during front cam with 5.0 and above.
Is it depends on the hardware?

**Comment by yuriy-budiyev** [comment]
Hello, I tested this library on android vrsions 4.4 to 8.1. Old camera API, which is used by my library is really bad. But to use new API, I should rise minimum SDK version to 21, which is not acceptable for now.
Focus and flash buttons only enabled if such features is supported by hardware.
Probably if you provide error log, and some pieces of your code, where you're using scanner, it will help me to understand the problem.

**Comment by yuriy-budiyev** [comment]
In 1.8.6 I added constants for front and back facing cameras: CodeScanner.CAMERA_BACK and CodeScanner.CAMERA_FRONT, you can use them in CodeScanner.setCamera method or constructor.
