### ISSUE TITLE
Could not find com.budiyev.android:code-scanner:2.1.0

### ISSUE THREAD

**Issue by csansoon** [yuriy-budiyev/code-scanner#120]

**Comment by koderstory** [comment]
Make sure you don't comment `jcenter` in build.gradle (project)
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}
```

**Comment by koderstory** [comment]
Hi @csansoon check this [#110](https://github.com/yuriy-budiyev/code-scanner/issues/110) if you don't want to use `jcenter()`

**Comment by yuriy-budiyev** [comment]
Check readme, migrated to JitPack.

**Comment by Sridhar54** [comment]
The dependency has been updated by the owner. Try using the 2.3.0 version as mentioned in this page. it worked for me:
https://github.com/yuriy-budiyev/code-scanner/blob/master/README.md

**Comment by raguvarank** [comment]
Failed to resolve: com.budiyev.android:code-scanner:2.1.0

**Comment by Sridhar54** [comment]
@raguvarank have you gone through the link i provided. it uses a forked version of the original dependency and you need to add the following in your dependency for this to work:
implementation 'com.github.yuriy-budiyev:code-scanner:2.3.0'
I think you are still using the original discontinued dependency.
