### ISSUE TITLE
Repository not available in mavenCentral

### ISSUE THREAD

**Issue by jaira** [yuriy-budiyev/code-scanner#123]
Hi Sir :)

Android studio is reporting to the console currently that jcenter() will be deprecated. Would you be willing to migrate this library to mavenCentral as well? Thank you!

**Comment by koderstory** [comment]
your issue has been discussed [here #110 ](https://github.com/yuriy-budiyev/code-scanner/issues/110)

**Comment by yuriy-budiyev** [comment]
Check readme, migrated to JitPack.
