### ISSUE TITLE
Cannot resolve class com.budiyev.android.codescanner.CodeScannerView

### ISSUE THREAD

**Issue by dulatello08** [yuriy-budiyev/code-scanner#127]
Cannot resolve class com.budiyev.android.codescanner.CodeScannerView
![image](https://user-images.githubusercontent.com/65179781/124083080-45ab2080-da6f-11eb-9792-749256b717ff.png)

**Comment by dulatello08** [comment]
Added jcent3r() in project gradle
Solved

**Comment by dulatello08** [comment]
Another problem
![image](https://user-images.githubusercontent.com/65179781/124086272-b4d64400-da72-11eb-8f4d-a752dca6c60d.png)

**Comment by dulatello08** [comment]
Fixed it with 
`import my.project.R;`
![Uploading image.png…]()

**Comment by dulatello08** [comment]
App crashes on virtual Pixel_3A
   
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: cs-init
    Process: net.dulatello08.medorg, PID: 6512
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:496)
        at android.hardware.Camera.open(Camera.java:398)
        at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835)
        at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x7807a8a57d50, tid 6554
D/goldfish-address-space: allocate: Ask for block of size 0x100
    allocate: ioctl allocate returned offset 0x3fdd5f000 size 0x2000
W/Gralloc4: allocator 4.x is not supported
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
I/Process: Sending signal. PID: 6512 SIG: 9

**Comment by ramupal2603** [comment]
I am facing the same issue  showing, Cannot resolve class com.budiyev.android.codescanner.CodeScannerView.

**Comment by dulatello08** [comment]
> I am facing the same issue showing, Cannot resolve class com.budiyev.android.codescanner.CodeScannerView.

Did you add implementation in app level gradle.build?
If yes try build and make sure that you didn't remove jcenter().

**Comment by abhijitunavane** [comment]
**I've solved this issue.**

1.  Added this dependency - implementation 'com.budiyev.android:code-scanner:2.1.0' by going to the project structure in file tab.
2. Then, go to the dependencies and press + button and add **com.budiyev.android:code-scanner:2.1.0** 
3. Apply and ok.
4. Now you can see the error is gone.

**Comment by yuriy-budiyev** [comment]
Moved to JitPack, see readme.
Check camera permissions and update to 2.1.2 for better error handling.

**Comment by prosyanoy** [comment]
Th

> **I've solved this issue.**
> 
> 1. Added this dependency - implementation 'com.budiyev.android:code-scanner:2.1.0' by going to the project structure in file tab.
> 2. Then, go to the dependencies and press + button and add **com.budiyev.android:code-scanner:2.1.0**
> 3. Apply and ok.
> 4. Now you can see the error is gone.

Didn't help

**Comment by yuriy-budiyev** [comment]
See README.MD and follow the steps. For R.*** - Alt + Enter -> Import. For "Fail to connect to camera service" - request permissions".
See sample appliation: https://github.com/yuriy-budiyev/lib-demo-app

**Comment by ChaudharyAmit** [comment]
It is not working.

**Comment by ChaudharyAmit** [comment]
giving some issues like dependency isn't loaded.
com.budiyev.android.codescanner.CodeScannerView, was not found in the project or the libraries.

**Comment by Varnitgithub** [comment]
> Cannot resolve class com.budiyev.android.codescanner.CodeScannerView ![image](https://user-images.githubusercontent.com/65179781/124083080-45ab2080-da6f-11eb-9792-749256b717ff.png)

change mavenCentral() with  jcenter() in setting.gradle

**Comment by lenilestari** [comment]
> Menambahkan jcent3r() dalam proyek gradle Terpecahkan

Thank you for your answer, it really helped me
