### ISSUE TITLE
Camera Quality issues

### ISSUE THREAD

**Issue by hassanalinali** [yuriy-budiyev/code-scanner#13]
The camera quality is really bad, I will look check the code myself but I'm not comparing to the original camera application quality, it doesn't even compare with the Zxing camera intent demo, it's usable on my Pixel 2 XL but not with my other test phones. Please let me know if we can do something regarding this.

**Comment by yuriy-budiyev** [comment]
Put a breakpoint here
https://github.com/yuriy-budiyev/code-scanner/blob/b23ec06e152317389d80b44c7e12543b8b604f17/src/main/java/com/budiyev/android/codescanner/CodeScanner.java#L777
and tell me values of all variables of this method at this moment (including mWidth and mHeight)

**Comment by yuriy-budiyev** [comment]
Don't forget to update to 1.8.5 before

**Comment by hassanalinali** [comment]
Will do, thank you for your fast response

**Comment by yuriy-budiyev** [comment]
And "sizes" from here
https://github.com/yuriy-budiyev/code-scanner/blob/d59ce2cdfd4ead5d17f3c20e06b35aab381435dc/src/main/java/com/budiyev/android/codescanner/Utils.java#L62

**Comment by yuriy-budiyev** [comment]
Seems like the promblem is in preview size, it's 720x1280 insead of 1080x1920.
Please give me a screenshot of the app

**Comment by yuriy-budiyev** [comment]
Fixed in 1.8.6
