### ISSUE TITLE
Launching implicit intent with scan result (Kotlin)

### ISSUE THREAD

**Issue by RunMildew** [yuriy-budiyev/code-scanner#144]
The ZXing scanner has the ability to take the returned URL and then launch an implicit intent, which allows one to immediately go into the designated site. However, seeing as though this scanner is slightly more Kotlin friendly, how exactly would I be able to launch an implicit intent with the scanner's returned result?

**Comment by yuriy-budiyev** [comment]
You should do it manually (propably with Intent.ACTION_VIEW) in DecodeCallback.
