### ISSUE TITLE
WARNING: [Processor] Library '/root/.gradle/caches/transforms-3/bbf181829bc5eaa48991144733491009/transformed/core-1.8.0-SNAPSHOT-api.jar'

### ISSUE THREAD

**Issue by Squall-Huang** [yuriy-budiyev/code-scanner#149]
> Task :app:hiltAggregateDepsDebug
WARNING: [Processor] Library '/root/.gradle/caches/transforms-3/bbf181829bc5eaa48991144733491009/transformed/core-1.8.0-SNAPSHOT-api.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/R$styleable'
 Example of support library reference: 'android/support/v4/app/INotificationSideChannel$Default'

**Comment by yuriy-budiyev** [comment]
Code scanner depends only on annotations and zxing.
