### ISSUE TITLE
I cannanot scan by using  phone camera

### ISSUE THREAD

**Issue by Mdsarowarhossain** [yuriy-budiyev/code-scanner#154]
![Screenshot_20220407-130700](https://user-images.githubusercontent.com/98280301/162140435-1000d276-2f33-43b4-bf50-a5e4d23a97a4.jpg)
kindly see this screenshot. why cannot scan

**Comment by Gl0deanR** [comment]
Try with these in your AndroidManifest.xml file
```
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
```
This is how it works for me.

**Comment by Mdsarowarhossain** [comment]
> Try with these in your AndroidManifest.xml file
> ```
> <uses-permission android:name="android.permission.CAMERA" />
> <uses-feature android:name="android.hardware.camera" />
> ```
> This is how it works for me.

Am add this. My main errror is am not get permission by pakckagemanager . Now it solved

**Comment by Gl0deanR** [comment]
> > Try with these in your AndroidManifest.xml file
> > ```
> > <uses-permission android:name="android.permission.CAMERA" />
> > <uses-feature android:name="android.hardware.camera" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how it works for me.
> 
> Am add this. My main errror is am not take permission by pakckagemanager . Now it solved

Awesome! Please close the issue now so others can see it is solved and see the solution if they need it.

**Comment by Mdsarowarhossain** [comment]
> > > Try with these in your AndroidManifest.xml file
> > > ```
> > > <uses-permission android:name="android.permission.CAMERA" />
> > > <uses-feature android:name="android.hardware.camera" />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This is how it works for me.
> > 
> > Am add this. My main errror is am not take permission by pakckagemanager . Now it solved
> 
> Awesome! Please close the issue now so others can see it is solved and see the solution if they need it.

Okay ❤️
