### ISSUE TITLE
Work on AndroidStudio not work in real phone

### ISSUE THREAD

**Issue by jimijangkrik** [yuriy-budiyev/code-scanner#155]
I just test your code before develop to my own version, your code doesn't work on real phone but can run on Android Studio. The new depedencies '2.1.2' doesn't work on activity_main.xml, first I was using the '2.1.0' depedencies, the budiyev can be recognized in Android Studio but when I've changed to '2.1.2' its not recognized by Android Studio. Any solution?

Best Regards,

Jimi

**Comment by Gl0deanR** [comment]
Hey Jimi,
I have an Android app that works just fine with:
`implementation 'com.github.yuriy-budiyev:code-scanner:2.1.2'`

Try going to Android Studio, click on "Build" then select "Clean Project" and then again go to "Build" and select "Rebuild Project".
It might be an Android Studio bug, not a library one.

![image](https://user-images.githubusercontent.com/36914801/164425165-66fcf4c5-26ad-448c-8583-f8e7252eb3ff.png)

**Comment by jimijangkrik** [comment]
> Hey Jimi, I have an Android app that works just fine with: `implementation 'com.github.yuriy-budiyev:code-scanner:2.1.2'`
> 
> Try going to Android Studio, click on "Build" then select "Clean Project" and then again go to "Build" and select "Rebuild Project". It might be an Android Studio bug, not a library one.
> 
> ![image](https://user-images.githubusercontent.com/36914801/164425165-66fcf4c5-26ad-448c-8583-f8e7252eb3ff.png)

That's worked well and smooth, yes your are right I was using Android Studio Bumblebee after updating some of my code not worked mostly problem with gradle and depedencies. Thank you @[Gl0deanR](https://github.com/Gl0deanR) for the small solution that I missed.
