### ISSUE TITLE
Flash triggering on (auto)focus

### ISSUE THREAD

**Issue by NorthyFN** [yuriy-budiyev/code-scanner#162]
On the Sony Xperia 5 the flash button doesn't work and every time the camera is focusing the flash comes on in low light situations (this might even make sense for some applications but isn't wanted here...) 
The flash doesn't activate when the autofocus mode is set to continous but is still does every time you click on the screen for manual focus. This seems to be a problem with the camera API similar to this problem https://stackoverflow.com/questions/28802276/how-to-stop-camera-flash-when-triggering-autofocus
If this is a problem because of the outdated camera API I don't see a way of fixing this without changing the API but it would still be great to hear your thoughts @yuriy-budiyev

**Comment by yuriy-budiyev** [comment]
Camera2 API migration is planned, but I'm not sure when in will happen. Also, I can debug only on Pixel 5 and Galaxy S10, so I can't help with your problem.

**Comment by NorthyFN** [comment]
Great, thanks for your reply!
