### ISSUE TITLE
Can we set radius to frame?

### ISSUE THREAD

**Issue by gajanandchouhan** [yuriy-budiyev/code-scanner#19]
Hi Thanks for providing library. I need scanner frame rounded. Can you provide a solution how to set radius to frame.

**Comment by gajanandchouhan** [comment]
One more thing I noticed. In some devices it is showing  some white preview and unable to scan. But when I start flash light than it gives clear preview and also gives scan result.

**Comment by yuriy-budiyev** [comment]
Do you mean rounded corners or circle frame?
I have some ideas about second issue, it should be fixed in next release.

**Comment by gajanandchouhan** [comment]
I means rounded corner like below image.
![lannisters-select-people](https://user-images.githubusercontent.com/29336713/41355151-706977ee-6f3e-11e8-9873-752914eccf1d.png)

**Comment by gajanandchouhan** [comment]
![lennister_qr_code](https://user-images.githubusercontent.com/29336713/41355183-839b59ea-6f3e-11e8-9a97-09045e5c0fac.jpg)
I need like this

**Comment by gajanandchouhan** [comment]
I mean rounded corner. that are four surrounding view finder view only need to set radius like 4dp.

**Comment by gajanandchouhan** [comment]
Hi @yuriy-budiyev  have you check about white preview issue? Pleas help if possible.

**Comment by yuriy-budiyev** [comment]
Bright preview in progress

**Comment by yuriy-budiyev** [comment]
Should be fixed in 1.9.1
