### ISSUE TITLE
Auto focus mode

### ISSUE THREAD

**Issue by Codewaves** [yuriy-budiyev/code-scanner#2]
Why FOCUS_MODE_CONTINUOUS_PICTURE or FOCUS_MODE_CONTINUOUS_VIDEO auto focus mode is not used? I think it will give more consistent result comparing to current auto focus implementation. Currently camera constantly resets focus and this looks really weird.

**Comment by yuriy-budiyev** [comment]
The thing is that this focus modes isn't really works on all devices, even if it's in the supported list of Camera.Preferences. For exampe, on Galaxy A5 2017 it isn't working. So, this wired mode is only the safe way to get auto focus to work on all devices that support it.

**Comment by Codewaves** [comment]
It will be good, if you can set autofocus interval then. Or even autofocus mode on a lower level.

**Comment by yuriy-budiyev** [comment]
Good idea, i'll implement this further versions.

**Comment by yuriy-budiyev** [comment]
Released in version 1.4.0
