### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by NickRimmer** [yuriy-budiyev/code-scanner#20]
Hey! Very nice component, thank you!
Is it possible to manage zoom of camera?

**Comment by duz17** [comment]
Hi, I join to this request
I'm working with front camera for scan and it's impossible to scan with default zoom (x1)
please open the api for that

**Comment by yuriy-budiyev** [comment]
I will implement this soon

**Comment by yuriy-budiyev** [comment]
Implemented in v1.9.2

**Comment by azizimusa** [comment]
Default zoom setting is already 0. But why it still zooming like 2x level. How do i completely disable zoom?
