### ISSUE TITLE
extending class is impossible

### ISSUE THREAD

**Issue by duz17** [yuriy-budiyev/code-scanner#21]
Hi, general request:
I needed some specification for my app, and couldn't do any changes/inheritance/access to fields
all classes are final or final & private(or accessible in the same package only)
fields are private (not protected) without getters
it's impossible to have small change without cloning the repository

please make it more accessible
thanks

**Comment by yuriy-budiyev** [comment]
Final classes and getters/setters needed for Kotlin compatibility. And I don't wont to give acess to "intestines" of library. If you need some concrete feature, feel free to ask here. I'm open to discussions.

**Comment by duz17** [comment]
I needed to enable zoom. did it with creating same package and reflection
second option was cloning and changing the code, which is not a good way for keep getting updates

most products need specification that libraries can't provide, that's why getters, setters and ability for inheritance is important

**Comment by yuriy-budiyev** [comment]
Zoom implemented in v1.9.2
