### ISSUE TITLE
Portrait decoding

### ISSUE THREAD

**Issue by riki-dexter** [yuriy-budiyev/code-scanner#24]
Hi @yuriy-budiyev ,
thank you for this library.
I'm using it in my app but I have an issue. When device is rotated in portrait mode only the first scan of a barcode takes about 20 seconds to decode. If I rotate device to landscape and then again in portrait, or if I start my app in landscape mode barcode decoding is immediate.

**Comment by riki-dexter** [comment]
Now I've notice some rare cases with this 20 seconds delay also in landscape mode.
I'm on a Samsung Galaxy Tab S3.
Thank you

**Comment by yuriy-budiyev** [comment]
Tested now on my Tab S3 (Android 8). Works fine, not so fast, but fine (3-5 sec)
