### ISSUE TITLE
Add a scan animating bar like Whatsapp

### ISSUE THREAD

**Issue by JobGetabu** [yuriy-budiyev/code-scanner#29]
![blog1](https://user-images.githubusercontent.com/22516895/43982994-086feb5a-9d01-11e8-8274-e736444078ed.gif)

option to add an animating scanner bar that moves up and down as it scans.

**Comment by AndyKD** [comment]
Any solution to this? I am also looking for this same..

**Comment by ArslanKathia** [comment]
i think using canvas + animation to do like this.

**Comment by JobGetabu** [comment]
check this tutorial
http://kunmii.blogspot.com/2018/01/building-animated-qr-scanner-viewfinder.html

**Comment by yuriy-budiyev** [comment]
You can just add the overlay view and implement the animation manually.
