### ISSUE TITLE
ScannerView layout error

### ISSUE THREAD

**Issue by Codewaves** [yuriy-budiyev/code-scanner#3]
If CodeScannerView is not full screen, all child items are shifted down by parent top offset value. For example, if CodeScannerView is centered vertically or has Top margin.
Workaround is to insert CodeScannerView into dummy LinearLayout, to make top offset 0.

**Comment by yuriy-budiyev** [comment]
Thanks for the report, in my project, this view is always sticked to the top of the parent layout. I'll try to fix this tomorrow.

**Comment by yuriy-budiyev** [comment]
Fixed in version 1.6.2
