### ISSUE TITLE
One file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'

### ISSUE THREAD

**Issue by waakobrian** [yuriy-budiyev/code-scanner#34]
When U Added  implementation 'com.budiyev.android:code-scanner:2.0.0', I get the above error in the issue title.

This is my configuration:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.ticket.ticketingsystem"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.budiyev.android:code-scanner:2.0.0'

}

**Comment by yuriy-budiyev** [comment]
To use version 2.0.0 and later you should migrate your project to [AndroidX](https://developer.android.com/topic/libraries/support-library/androidx-overview)
