### ISSUE TITLE
Touch and focus bug

### ISSUE THREAD

**Issue by livedota** [yuriy-budiyev/code-scanner#36]
**Current Behavior**
Focus by touch stop working

**Expected Behavior**
Focus by touch should always work

**Step to reproduce bug**
1.Touch the screen to start focus
2. Touch the screen before focus finish
3. Touch the screen to perform focus again but nothing happened

**Setting used**
AutoFocusEnabled(false);
TouchFocusEnabled(true);

**Comment by yuriy-budiyev** [comment]
Fixed in version 2.0.1
