### ISSUE TITLE
Scanner orientation

### ISSUE THREAD

**Issue by innoflash** [yuriy-budiyev/code-scanner#37]
Hey Yuriy and fellow developers, i would want to ask how to change the scanner orientation using whether the `ScannerView `or `CodeScanner `class. Or rather can you help me to make the scanner be orientation independent (_scan in both orientation states_). so far it seems to be portrait fixed when scanning **PDF417**, **QR Code** is working in all orientation

Cheers

**Comment by yuriy-budiyev** [comment]
It depends on barcode type. Some of them are orientation-sensitive, some not.

**Comment by innoflash** [comment]
sure, you think there can be a work-around for those that are orientation-sensitive?

**Comment by yuriy-budiyev** [comment]
There are no simple workaround

**Comment by innoflash** [comment]
thanks a lot buddy, i love your library by the way

**Comment by yuriy-budiyev** [comment]
Thank you :)
