### ISSUE TITLE
QR-Scanning not working

### ISSUE THREAD

**Issue by Trust-Coder** [yuriy-budiyev/code-scanner#38]
I'm having trouble in scanning the QR codes. I'm attaching a high sample image of QR code making trouble. 
![qr code](https://user-images.githubusercontent.com/35214797/46620405-1412fe00-cb3e-11e8-87ad-12a09a139a72.jpg)

its working file with other scanners which have used same Xing Library but don't know why giving issue on this one.  I have also tried to enabled all formats by         `mCodeScanner.setFormats(CodeScanner.ALL_FORMATS);
`
but still issue remain same. Can you please specify the solution ASAP.

**Comment by yuriy-budiyev** [comment]
Just tested with [sample app](https://github.com/yuriy-budiyev/lib-demo-app) on Pixel 2XL - works fine.
![Screenshot](https://user-images.githubusercontent.com/11834224/46724125-0feff900-cc82-11e8-86e9-9b8e03948a1b.jpg)
