### ISSUE TITLE
Layoutparams are wrongly chosen. 

### ISSUE THREAD

**Issue by Orrimp** [yuriy-budiyev/code-scanner#39]
I am using this library with a dialog and the preview and its internal representation SurfaceView mPreviewView; has bad Layoutparams. new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT

As a consequence the preview surface view is outside of the bound of my dialog. Is there a way to fix it?

**Comment by yuriy-budiyev** [comment]
This issue isn't related to layout params (parent of SurfaceView is CodeScannerView). It's related to SurfaceView itself. I don't recommend to use scanner in dialog. For now, there are no workaround to solve this problem.
