### ISSUE TITLE
Camera not initializing

### ISSUE THREAD

**Issue by gangd42** [yuriy-budiyev/code-scanner#44]
In logcat: **W/CameraBase: An error occurred while connecting to camera: 0**

```
mCodeScanner.setCamera(findCamera());
mCodeScanner.startPreview();

private int findCamera() {
    int numberOfCameras = Camera.getNumberOfCameras();
        int cameraId = 0;
        for (int i = 0; i < numberOfCameras; i++) {
            Camera.CameraInfo info = new Camera.CameraInfo();
            Camera.getCameraInfo(i, info);
            if (info.facing == Camera.CameraInfo.CAMERA_FACING_BACK) {
                cameraId = i;
                break;
            }
        }
        return cameraId;
}
```

**Comment by gangd42** [comment]
![logcat_image](https://user-images.githubusercontent.com/16123051/47984467-b5b94b00-e0fc-11e8-9710-024b7a238aa3.png)

**Comment by yuriy-budiyev** [comment]
Have you requested the camera permission?

**Comment by gangd42** [comment]
Yes

**Comment by yuriy-budiyev** [comment]
Have you set an ErrorCallback?
Is it happens only when you are setting camera manually only or anyway?

**Comment by gangd42** [comment]
I am using android device with API 19, i.e., Kitkat 4.4.4

**Comment by yuriy-budiyev** [comment]
Can you do a screenshot with stack trace?
ex:

**Comment by yuriy-budiyev** [comment]
And also, Code Scanner will use first bask-facing camera by default.

**Comment by yuriy-budiyev** [comment]
Are you using cmera only by Code Scanner or not? Probably, you haven't released the camera before usage. Also, will be good to take a look at your source code.
