### ISSUE TITLE
Animated red scanning bar

### ISSUE THREAD

**Issue by malhobayyeb** [yuriy-budiyev/code-scanner#45]
How can we add a moving scanning line as in the following image:

[Moving Red Line](https://raw.githubusercontent.com/SudarAbisheck/ZXing-Orient/master/screenshots/screenshot_1.png)

**Comment by yuriy-budiyev** [comment]
You can jest add the overlay view and implement the animation manually.

**Comment by pg55** [comment]
But how to fix the scanner line(i.e.width) withing camera view.Please give the code also for how to add overlay.Thanks
