### ISSUE TITLE
Project not building 'META-INF/proguard/androidx-annotations.pro'

### ISSUE THREAD

**Issue by sidsaxena0** [yuriy-budiyev/code-scanner#47]
Project building is failed with error : 

More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'

Please help with it.

**Comment by mohammad425** [comment]
add this code in build.gradle : 

```
android {
...

packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }
}
```

**Comment by yuriy-budiyev** [comment]
You should migrate your project to AndroidX, android.support libraries are now deprecated.
