### ISSUE TITLE
Android Studio cannot import class import com.google.zxing.Result;

### ISSUE THREAD

**Issue by CodeIgniter00** [yuriy-budiyev/code-scanner#50]
Android Studio cannot import class import **com.google.zxing.Result** but at the same time the code is compiled normally.

Tried to do a clean up project - did not help.
If you know what the problem is, then please help me a lot.

**Comment by yuriy-budiyev** [comment]
Try invalidate caches, restart, clean and rebuild.
Or re-import project.
