### ISSUE TITLE
code to bitmap error

### ISSUE THREAD

**Issue by s-ilnar** [yuriy-budiyev/code-scanner#56]
Hello!

My Code:
BarcodeUtils.encodeBitmap(code, BarcodeFormat.EAN_13, 400, 150)

exception:
Process: ru.ilnarsoultanov.pivovaroff, PID: 14959
    java.lang.ArrayIndexOutOfBoundsException: length=1950; index=1953

What am I doing wrong?

**Comment by yuriy-budiyev** [comment]
Encoding and decoding images are done by ZXing library.
