### ISSUE TITLE
Scanner Activity stays frozen for a few seconds when closing

### ISSUE THREAD

**Issue by enriquebautista** [yuriy-budiyev/code-scanner#59]
Hi! Nice work. But sometimes when opening and closing several times, the activity scanner takes a long time to open and in the log it shows the error: Camera: Error 100 and it opens after a few seconds. And sometimes when you want to close the activity scanner it stays frozen for a few seconds and the activity is closed. Thanks.

XML:
`<com.budiyev.android.codescanner.CodeScannerView
            android:id="@+id/scanner_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:frameColor="@color/scanner_frame_color"
            app:autoFocusButtonVisible="false"
            app:flashButtonVisible="false"
            app:frameThickness="4dp"
            app:frameCornersRadius="2dp" />`

Kotlin:
`import android.os.Bundle
import android.view.View.VISIBLE
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.budiyev.android.codescanner.CodeScanner
import com.budiyev.android.codescanner.DecodeCallback
import com.budiyev.android.codescanner.ErrorCallback
import com.cloudsourceit.pnletouroperador.R
import com.google.zxing.BarcodeFormat
import kotlinx.android.synthetic.main.activity_scanner.*

class ScannerActivity : AppCompatActivity() {

    private lateinit var scanner: CodeScanner

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_scanner)
        setSupportActionBar(toolbar)
        // We use our own toolbar title, so hide the default one
        supportActionBar?.setDisplayShowTitleEnabled(false)
        toolbar.setNavigationOnClickListener {
            finish()
        }
        scanner = CodeScanner(this, scanner_view).apply {
            this.formats = listOf(BarcodeFormat.QR_CODE)
            this.decodeCallback = DecodeCallback {
                image_success.visibility = VISIBLE
                Toast.makeText(this@ScannerActivity, "Scan result: ${it.text}", Toast.LENGTH_LONG).show()
            }
            this.errorCallback = ErrorCallback {
                Toast.makeText(this@ScannerActivity, "Camera initialization error: ${it.message}",
                    Toast.LENGTH_LONG).show()
            }
        }
    }

    override fun onResume() {
        super.onResume()
        scanner.startPreview()
    }

    override fun onPause() {
        scanner.releaseResources()
        super.onPause()
    }
}`

**Comment by yuriy-budiyev** [comment]
https://developer.android.com/reference/android/hardware/Camera.html#CAMERA_ERROR_SERVER_DIED
