### ISSUE TITLE
Take much time 

### ISSUE THREAD

**Issue by gehadfatah** [yuriy-budiyev/code-scanner#6]
app take much time to recognize the barcode pattern

**Comment by yuriy-budiyev** [comment]
What library version and device are you using?

**Comment by gehadfatah** [comment]
Using xiami mi a1 with android 8  device 
and version of library is 1.8.0

**Comment by yuriy-budiyev** [comment]
Can you put a breakpoint here
https://github.com/yuriy-budiyev/code-scanner/blob/aa03daaf27dca56d0acf7bd305ab808341450ed6/src/main/java/com/budiyev/android/codescanner/DecodeTask.java#L59
and tell me values of fields of the class (excluding mImage)?

**Comment by yuriy-budiyev** [comment]
Try version 1.8.1
Btw, on all of my test devices scan takes about 1-2 seconds.

**Comment by yuriy-budiyev** [comment]
Try version 1.8.1
Btw, on all of my test devices scan takes about 1-2 seconds.
