### ISSUE TITLE
Top-left icon in QR scanner view do nothing

### ISSUE THREAD

**Issue by agalfioni** [yuriy-budiyev/code-scanner#60]
Hi, great lib!

I want to know for what is the icon in the top-left corner in QR scanner view, i click on it but nothing happens.

Regards

**Comment by yuriy-budiyev** [comment]
This is auto focus switch

**Comment by yuriy-budiyev** [comment]
You can hide all butons with attributes

**Comment by agalfioni** [comment]
Great! Ty @yuriy-budiyev 

I will close this issue, regards!
