### ISSUE TITLE
Can I custome UI scanner?

### ISSUE THREAD

**Issue by thanhtranduc** [yuriy-budiyev/code-scanner#61]
Hi All
I can not override CodeScannerView to custom UI that I want, Can I custom the UI scanner?

**Comment by yuriy-budiyev** [comment]
What customization do you need? You can customize the view by attributes.

**Comment by thanhtranduc** [comment]
I'm so appreciate you reply my comment. I saw all of class are final it is impossible to override what I want. basically I wanna change position ViewFinderView on the screen, it is center right now sir!!!!

**Comment by mf-mindcrewtech** [comment]
@yuriy-budiyev same question here, how can I change the ViewFinder screen position,

@thanhtranduc did you found any solution?
