### ISSUE TITLE
1D code recognition when code is vertical

### ISSUE THREAD

**Issue by danndi** [yuriy-budiyev/code-scanner#7]
Hi,

Is it possible to add feature to recognize 1D barcode (EAN) when code is placed vertically? 

The application is made to be portrait only, but I need to be able to scan codes in all orientations without moving the device. 

Here is the screenshot from my app where you can see what do I need.

![screenshot_20180225-220649](https://user-images.githubusercontent.com/10066429/36646698-72bf82b2-1a7b-11e8-8c73-c7e40316a480.png)

Thank you for your help.

**Comment by yuriy-budiyev** [comment]
I don't think this is possible becuse ZXing library is used to decode images (https://github.com/zxing/zxing).
