### ISSUE TITLE
How to ask runtime permissions for Camera?

### ISSUE THREAD

**Issue by hoseinmoradi** [yuriy-budiyev/code-scanner#76]
my app crashed in onCreate while called codescanner.startpreview() because my app dont access to camera permissions . please help me :/

**Comment by hoseinmoradi** [comment]
My problem was solved this way : 

`oncreate() ->
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (checkSelfPermission(Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                mPermissionGranted = false;
                requestPermissions(new String[] {Manifest.permission.CAMERA}, RC_PERMISSION);
            } else {
                mPermissionGranted = true;
            }
        } else {
            mPermissionGranted = true;
        }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        if (requestCode == RC_PERMISSION) {
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                mPermissionGranted = true;
                mCodeScanner.startPreview();
            } else {
                mPermissionGranted = false;
            }
        }
    }`

**Comment by yuriy-budiyev** [comment]
See sample app: https://github.com/yuriy-budiyev/lib-demo-app
