### ISSUE TITLE
After the barcode is scanned , the codescanner will the stepped

### ISSUE THREAD

**Issue by hoseinmoradi** [yuriy-budiyev/code-scanner#77]
`

public class SellActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener{

    private List<ProductModel> ProductDataDetails = new ArrayList<ProductModel>();
    private List<String> barcodeModels = new ArrayList<>();
    private static final int RC_PERMISSION = 10;
    private boolean mPermissionGranted;
    private int TotalFactorPrice = 0;
    private String barcode_index;
    private CodeScanner mCodeScanner;
    private Toolbar toolbar;
    private DrawerLayout drawer_layout;
    private BarcodeListAdapter barcodeListAdapter;
    private RetrofitRoutes routes;
    private MyButton btnSubmitOrder;
    private MyTextView txtTotalFactorPrice;
    private NavigationView nav_view;
    private DecimalFormat decimalFormat;
    private FloatingActionButton fab_refresh;
    private RecyclerView recyclerview_list;
    private Intent intent;
    private BarcodeModel barcodemodel;
    private ProductModel product;
    private CodeScannerView scanner_view;
    private Utility utility;
    RecyclerView.LayoutManager mLayoutManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sell);
        setSupportActionBar(toolbar);
        bindView();
        utility = new Utility(this);
        barcodeModels.clear();
        ProductDataDetails.clear();
        routes = RetrofitUtils.getCallback();
        mLayoutManager = new LinearLayoutManager(getApplicationContext());
        recyclerview_list.setLayoutManager(mLayoutManager);
        recyclerview_list.setItemAnimator(new DefaultItemAnimator());
        recyclerview_list.setAdapter(barcodeListAdapter);
        barcodeListAdapter = new BarcodeListAdapter(this,ProductDataDetails);
        scanner_view = findViewById(R.id.scanner_view);
        mCodeScanner = new CodeScanner(this, scanner_view);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer_layout, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer_layout.addDrawerListener(toggle);

        toggle.syncState();
        nav_view.setNavigationItemSelectedListener(this);
        mCodeScanner.setDecodeCallback(new DecodeCallback() {
                @SuppressLint("WrongThread")
                @Override
                public void onDecoded(@NonNull final Result result) {
                    SellActivity.this.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            barcode_index = result.getText();
                            if (!barcodeModels.contains(barcode_index)){

                                barcodeModels.add(barcode_index);
                                routes.getDetailProductByBarcodeID(1,1,barcode_index).enqueue(new Callback<ProductModel>() {
                                    @Override
                                    public void onResponse(Call<ProductModel> call, Response<ProductModel> response) {
                                        if (response.code() == 200)
                                        {
                                            if (response.body().getBarcode().equalsIgnoreCase(barcode_index))
                                            {
                                                product = response.body();
                                            }else{
                                            }
                                        }else{
                                        }
                                    }

                                    @Override
                                    public void onFailure(Call<ProductModel> call, Throwable t) {
                                        Log.d("234324",  t.getMessage());
                                    }
                                });

                                ProductDataDetails.add(product);
                                Log.d("67434535", "run: " + ProductDataDetails.size());
                                Collections.reverse(ProductDataDetails);
                            }else{
                            }

                         }
                    });
                }

        });

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (checkSelfPermission(Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                mPermissionGranted = false;
                requestPermissions(new String[] {Manifest.permission.CAMERA}, RC_PERMISSION);
            } else {
                mPermissionGranted = true;
            }
        } else {
            mPermissionGranted = true;
        }
    }
    void bindView() {
        recyclerview_list = findViewById(R.id.recyclerview_list);
        toolbar = findViewById(R.id.toolbar);
        drawer_layout = findViewById(R.id.drawer_layout);
        nav_view = findViewById(R.id.nav_view);
        btnSubmitOrder = findViewById(R.id.submit_order);
        txtTotalFactorPrice= findViewById(R.id.txtTotalFactorPrice);
        fab_refresh = findViewById(R.id.fab_refresh);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        if (requestCode == RC_PERMISSION) {
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                mPermissionGranted = true;
                mCodeScanner.startPreview();
            } else {
                mPermissionGranted = false;
            }
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (mPermissionGranted) {
            mCodeScanner.startPreview();
        }
    }

    @Override
    protected void onPause() {
        mCodeScanner.releaseResources();
        super.onPause();
    }
}
`

**Comment by yuriy-budiyev** [comment]
mCodeScanner.setScanMode(ScanMode.CONTINUOUS);
